version: 2
jobs:
  build:
    macos:
      xcode: "9.4"
    environment:
      FASTLANE_LANE: build
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Fastlane
          command: fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  upload:
    macos:
      xcode: "9.4"
    environment:
      FASTLANE_LANE: upload
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Fastlane
          command: fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output/Game.ipa

workflows:
  version: 2
  build-upload:
    jobs:
      - build
      - upload:
          filters:
            branches:
              only: develop
          requires:
            - build
